@userName = SSS
@Api_HostAddress = http://localhost:5001

### Get Basket by Username
GET {{Api_HostAddress}}/basket/{{userName}}
Content-Type: application/json

### Store Basket (Insert-Update)
POST {{Api_HostAddress}}/basket
Content-Type: application/json

{
    "Cart":
        {
            "userName": "{{userName}}",
            "items": [
                {
                "productId": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                "productName": "iPhone 13",
                "quantity": 1,
                "color": "Red",
                "price": 999.99
                },
                {
                "productId": "c9bf9e57-1685-4c89-bafb-ff5af830be8a",
                "productName": "Samsung Galaxy S21",
                "quantity": 2,
                "color": "Blue",
                "price": 799.99
                }
            ]
        }
}

### Delete Basket by Username
DELETE {{Api_HostAddress}}/basket/{{userName}}
Content-Type: application/json

### Checkout Basket
POST {{Api_HostAddress}}/basket/checkout
Content-Type: application/json

{
  "userName": "{{userName}}",
  "items": [
    {
      "productId": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
      "productName": "iPhone 13",
      "quantity": 1,
      "color": "Red",
      "price": 999.99
    },
    {
      "productId": "c9bf9e57-1685-4c89-bafb-ff5af830be8a",
      "productName": "Samsung Galaxy S21",
      "quantity": 2,
      "color": "Blue",
      "price": 799.99
    }
  ],
  "totalPrice": 2599.97
}