
@Api_HostAddress = http://localhost:5000

# List all products
GET {{Api_HostAddress}}/products?pageNumber=4&pageSize=2
Content-Type: application/json

###

# Fetch a specific product by ID
@id = 0192ce19-f2bc-4761-a66e-a114a8e347d7
GET {{Api_HostAddress}}/products/{{id}}
Content-Type: application/json

###

# Get products by category
@category = Cat
GET {{Api_HostAddress}}/products/category/{{category}}
Content-Type: application/json

###

# Create a new product
POST {{Api_HostAddress}}/products
Content-Type: application/json

{
    "name": "Sample Product",
    "category": ["Satan1", "Satan3"],
    "description": "This is a sample Satan",
    "imageFile": "image.jpg",
    "price": 150.00
}

###

# Update a product by ID
PUT {{Api_HostAddress}}/products
Content-Type: application/json

{
    "id": "0192cdfd-a3a6-49fc-b88d-b01aaae605fa",
    "name": "Updated Name Product",
    "category": [
        "Category1",
        "Category2",
        "CUpdated12"
    ],
    "description": "Updated description 2nd",
    "imageFile": "imageUpdated.jpg",
    "price": 133
}

###

# Remove a product by ID
@delete_id = 0192cfa5-3e08-4035-bf32-d3e1fed46893
DELETE {{Api_HostAddress}}/products/{{delete_id}}
Content-Type: application/json

###

# Remove a product by ID
Get {{Api_HostAddress}}/health
Content-Type: application/json